const cards = [
    { "name": "Mirties baronė Vaela", "image": "vaela.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 600, "rarity": "Legendinis" },
    { "name": "Malduras Juodasis", "image": "malduras_juodasis.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 500, "rarity": "Legendinis" },
    { "name": "Eldoras Sielų Meistras", "image": "eldoras_sielu_meistras.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 300, "rarity": "Epiškas" },
    { "name": "Pagiežingasis Fenrikas", "image": "fenrikas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Epiškas" },
    { "name": "Bišopas Argalurdas", "image": "argalurdas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 500, "rarity": "Epiškas" },
    { "name": "Mirties šauksmas", "image": "mirties_sauksmas.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 900, "rarity": "Epiškas" },
    { "name": "Varinas kapų gynėjas", "image": "varinas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Unikalus" },
    { "name": "Sargonas kraugerys", "image": "sargonas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 500, "rarity": "Unikalus" },
    { "name": "Maro Juokdarys", "image": "maro_juokdarys.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 500, "rarity": "Unikalus" },
    { "name": "Kaulų rinkėjas", "image": "kaulu_rinkejas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Unikalus" },
    { "name": "Vėlių Šauklė", "image": "veliu_saukle.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Unikalus" },
    { "name": "Sielų pabudimas", "image": "sielu_pabudimas.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 500, "rarity": "Unikalus" },
    { "name": "Zanara Tamsioji", "image": "zanara.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 200, "rarity": "Magiškas" },
    { "name": "Belmoras Žiaurusis", "image": "belmoras.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Magiškas" },
    { "name": "Zombis pranašas", "image": "zombis_pranasas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Anera Pūvančioji", "image": "anera.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Magiškas" },
    { "name": "Skausmo Šauklys", "image": "skausmo_sauklys.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Negyvėlių orda", "image": "negyveliu_orda.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 500, "rarity": "Magiškas" },
    { "name": "Prakeiktųjų šauksmas", "image": "prakeiktuju_sauksmas.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 600, "rarity": "Magiškas" },
    { "name": "Nekromanto Žvilgsnis", "image": "nekromanto_zvilgsnis.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 700, "rarity": "Magiškas" },
    { "name": "Kapinyno bastūnas", "image": "kapinyno_bastunas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Paprastas" },
    { "name": "Kūnų draskytojas", "image": "kunu_draskytojas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 500, "rarity": "Paprastas" },
    { "name": "Šmėkla klajoklė", "image": "smekla_klajokle.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 200, "rarity": "Paprastas" },
    { "name": "Maro karys", "image": "maro_karys.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 500, "rarity": "Paprastas" },
    { "name": "Kapinių vagis", "image": "kapiniu_vagis.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 200, "rarity": "Paprastas" },
    { "name": "Šešėlių šmėkla", "image": "seseliu_smekla.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 600, "rarity": "Paprastas" },
    { "name": "Zombis klajoklis", "image": "zombis_klajoklis.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 300, "rarity": "Paprastas" },
    { "name": "Nakties tarnas", "image": "nakties_tarnas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Paprastas" },
    { "name": "Kūnų rijikas", "image": "kunu_rijikas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 300, "rarity": "Paprastas" },
    { "name": "Tamsos Ritualas", "image": "tamsos_ritualas.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 300, "rarity": "Paprastas" },
    { "name": "Elvira Melvija", "image": "elvira_melvija.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 600, "rarity": "Legendinis" },
    { "name": "Lindara Vingrė", "image": "lindara_vingre.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 800, "rarity": "Legendinis" },
    { "name": "Alchemikų Fortas", "image": "alchemiku_fortas.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 700, "rarity": "Epiškas" },
    { "name": "Germundas Dringis", "image": "germundas_dringis.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 500, "rarity": "Epiškas" },
    { "name": "Tvirbutis Mirka", "image": "tvirbutis_mirka.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 600, "rarity": "Epiškas" },
    { "name": "Sprogstanti magija", "image": "sprogstanti_magija.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 700, "rarity": "Epiškas" },
    { "name": "Atgalinis smūgis", "image": "atgalinis_smugis.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 400, "rarity": "Epiškas" },
    { "name": "Edmundas Žvarba", "image": "edmundas_zvarba.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 600, "rarity": "Unikalus" },
    { "name": "Selma Zylė", "image": "selma_zyle.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 500, "rarity": "Unikalus" },
    { "name": "Lindara Šilė", "image": "lindara_sile.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 400, "rarity": "Unikalus" },
    { "name": "Jorūnė Tamsa", "image": "jorune_tamsa.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 400, "rarity": "Unikalus" },
    { "name": "Laumės kerštas", "image": "laumes_kerstas.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 600, "rarity": "Unikalus" },
    { "name": "Bandos jausmas", "image": "bandos_jausmas.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 500, "rarity": "Unikalus" },
    { "name": "Apokaliptinė audra", "image": "apokaliptine_audra.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 700, "rarity": "Unikalus" },
    { "name": "Fabijus Kintis", "image": "fabijus_kintis.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 400, "rarity": "Magiškas" },
    { "name": "Markas Žalvarnis", "image": "markas_zalvarnis.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 500, "rarity": "Magiškas" },
    { "name": "Narmintas Žvabris", "image": "narmintas_zvabris.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 500, "rarity": "Magiškas" },
    { "name": "Servina Sidabrė", "image": "servina_sidabre.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 200, "rarity": "Magiškas" },
    { "name": "Benediktas Rūkas", "image": "benediktas_rukas.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Magiškas" },
    { "name": "Eustachijus Silas", "image": "eustachijus_silas.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 700, "rarity": "Magiškas" },
    { "name": "Elementų kamuoliai", "image": "elementu_kamuoliai.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 700, "rarity": "Magiškas" },
    { "name": "Paslėpta Galia", "image": "paslepta_galia.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Magiškas" },
    { "name": "Gynybinė aura", "image": "gynybine_aura.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 200, "rarity": "Magiškas" },
    { "name": "Stichijų Skydas", "image": "stichiju_skydas.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Magiškas" },
    { "name": "Branas Vėjūnas", "image": "branas_vejunas.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 600, "rarity": "Paprastas" },
    { "name": "Vilnė Saulinė", "image": "vilne_sauline.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 100, "rarity": "Paprastas" },
    { "name": "Magiški atradimai", "image": "magiski_atradimai.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Paprastas" },
    { "name": "Sekinančios stichijos", "image": "sekinancios_stichijos.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 400, "rarity": "Paprastas" },
    { "name": "Sapnų Kerai", "image": "sapnu_kerai.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 500, "rarity": "Paprastas" },
    { "name": "Kerų Atsiskleidimas", "image": "keru_atsiskleidimas.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Paprastas" },
    { "name": "Apsukrusis Slelk’as", "image": "slelkas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 600, "rarity": "Legendinis" },
    { "name": "Egzekutorius Prol’as", "image": "prolas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 800, "rarity": "Legendinis" },
    { "name": "Vrold’as", "image": "vroldas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Epiškas" },
    { "name": "Gurd’as", "image": "gurdas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 500, "rarity": "Epiškas" },
    { "name": "Zabelx’as", "image": "zabelxas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 200, "rarity": "Epiškas" },
    { "name": "Apgaulingos taktikos", "image": "apgaulingos_taktikos.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 800, "rarity": "Epiškas" },
    { "name": "Tretvoc’as", "image": "tretvocas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 400, "rarity": "Unikalus" },
    { "name": "Dručkis Onvac’as", "image": "onvacas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 600, "rarity": "Unikalus" },
    { "name": "Taldi", "image": "taldi.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Unikalus" },
    { "name": "Vramaarx’as", "image": "vramaarxas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 400, "rarity": "Unikalus" },
    { "name": "Retaliacija", "image": "retaliacija.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Unikalus" },
    { "name": "Kovos eskalacija", "image": "kovos_eskalacija.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 500, "rarity": "Unikalus" },
    { "name": "Maitėdų būrys", "image": "maitedu_burys.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 500, "rarity": "Unikalus" },
    { "name": "Orm’as", "image": "ormas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 200, "rarity": "Magiškas" },
    { "name": "Wrydiord’as", "image": "wrydiordas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 900, "rarity": "Magiškas" },
    { "name": "Gilez’as", "image": "gilezas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 500, "rarity": "Magiškas" },
    { "name": "Kalx’as", "image": "kalxas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Magiškas" },
    { "name": "Ubbes’as", "image": "ubbesas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 200, "rarity": "Magiškas" },
    { "name": "Jakz’as", "image": "jakzas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 400, "rarity": "Magiškas" },
    { "name": "Drybs’as", "image": "drybsas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 500, "rarity": "Magiškas" },
    { "name": "Grurk’as", "image": "grurkas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 400, "rarity": "Paprastas" },
    { "name": "Edaald’as", "image": "edaaldas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 600, "rarity": "Paprastas" },
    { "name": "Wrosxa", "image": "wrosxa.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 400, "rarity": "Paprastas" },
    { "name": "Srefėja", "image": "srefeja.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Paprastas" },
    { "name": "Ienka", "image": "ienka.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 200, "rarity": "Paprastas" },
    { "name": "Zrusb’as", "image": "zrusbas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 100, "rarity": "Paprastas" },
    { "name": "Wynsa", "image": "wynsa.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 100, "rarity": "Paprastas" },
    { "name": "Frybs’as", "image": "frybsas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 400, "rarity": "Paprastas" },
    { "name": "Antras kvėpavimas", "image": "antras_kvepavimas.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Paprastas" },
    { "name": "Pelkių palyda", "image": "pelkiu_palyda.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 100, "rarity": "Paprastas" },
    { "name": "Oglor’as klaidintojas", "image": "ogloras_klaidintojas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 500, "rarity": "Legendinis" },
    { "name": "Didysis Belzatoras", "image": "didysis_belzatoras.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 800, "rarity": "Legendinis" },
    { "name": "Rajūnas Pak-erael’is", "image": "rajunas_pak_eraelis.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 600, "rarity": "Epiškas" },
    { "name": "Klastingoji Aelot’ė", "image": "klastingoji_aelote.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 500, "rarity": "Epiškas" },
    { "name": "Zorzok’as alkanasis", "image": "zorzokas_alkanasis.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 600, "rarity": "Epiškas" },
    { "name": "Trinak’as kerštingasis", "image": "trinakas_kerskingasis.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 600, "rarity": "Epiškas" },
    { "name": "Kryžkėlės demonas", "image": "kryzkeles_demonas.png", "type": "Burtas", "faction": "Demonų orda", "cost": 500, "rarity": "Epiškas" },
    { "name": "Jarot’as", "image": "jarotas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 300, "rarity": "Unikalus" },
    { "name": "Mubaal’as", "image": "mubaalas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 400, "rarity": "Unikalus" },
    { "name": "Digolan’as", "image": "digolanas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 400, "rarity": "Unikalus" },
    { "name": "Riglek’as", "image": "riglekas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 600, "rarity": "Unikalus" },
    { "name": "Gazzar’a", "image": "gazzara.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 500, "rarity": "Unikalus" },
    { "name": "Kraujas už kraują", "image": "kraujas_uz_krauja.png", "type": "Burtas", "faction": "Demonų orda", "cost": 600, "rarity": "Unikalus" },
    { "name": "Pragaro Liepsna", "image": "pragaro_liepsna.png", "type": "Burtas", "faction": "Demonų orda", "cost": 500, "rarity": "Unikalus" },
    { "name": "Vethagog’o kalnas", "image": "vethagogo_kalnas.png", "type": "Burtas", "faction": "Demonų orda", "cost": 400, "rarity": "Unikalus" },
    { "name": "Prakeiktasis žvėris", "image": "prakeiktasis_zveris.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 500, "rarity": "Magiškas" },
    { "name": "Dyglių velnias", "image": "dygliu_velnias.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 300, "rarity": "Magiškas" },
    { "name": "Zhileg’as", "image": "zhilegas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 700, "rarity": "Magiškas" },
    { "name": "Gargarmaras", "image": "gargarmaras.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 400, "rarity": "Magiškas" },
    { "name": "Geralel’as", "image": "geralelas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 500, "rarity": "Magiškas" },
    { "name": "Velnio advokatas", "image": "velnio_advokatas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 400, "rarity": "Magiškas" },
    { "name": "Demoniška akistata", "image": "demoniska_akistata.png", "type": "Burtas", "faction": "Demonų orda", "cost": 500, "rarity": "Magiškas" },
    { "name": "Demoniška įžvalga", "image": "demoniska_izvalga.png", "type": "Burtas", "faction": "Demonų orda", "cost": 300, "rarity": "Magiškas" },
    { "name": "Gilus pavydas", "image": "gilus_pavydas.png", "type": "Burtas", "faction": "Demonų orda", "cost": 400, "rarity": "Magiškas" },
    { "name": "Tamsios mintys", "image": "tamsios_mintys.png", "type": "Burtas", "faction": "Demonų orda", "cost": 300, "rarity": "Magiškas" },
    { "name": "Mirofalg’as", "image": "mirofalgas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 500, "rarity": "Paprastas" },
    { "name": "Khem’as", "image": "khemas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 200, "rarity": "Paprastas" },
    { "name": "Pragaro vartų sargas", "image": "pragaro_vartu_sargas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 300, "rarity": "Paprastas" },
    { "name": "Pelkių velnias", "image": "pelkiu_velnias.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 200, "rarity": "Paprastas" },
    { "name": "Velniūkštis", "image": "velniukstis.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 100, "rarity": "Paprastas" },
    { "name": "Alarikas Teisusis", "image": "alarikas_teisusis.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 700, "rarity": "Legendinis" },
    { "name": "Gunteris Narsusis", "image": "gunteris_narsusis.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 800, "rarity": "Legendinis" },
    { "name": "Seras Goldbergeris", "image": "seras_goldbergeris.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 700, "rarity": "Epiškas" },
    { "name": "Garbingasis Ulbas", "image": "garbingasis_ulbas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 500, "rarity": "Epiškas" },
    { "name": "Kapitonas Arnulfas", "image": "kapitonas_arnulfas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 600, "rarity": "Epiškas" },
    { "name": "Bernardas gynėjas", "image": "bernardas_gynejas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 600, "rarity": "Epiškas" },
    { "name": "Ordino apsuptis", "image": "ordino_apsuptis.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 600, "rarity": "Epiškas" },
    { "name": "Matihilda", "image": "matihilda.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 500, "rarity": "Unikalus" },
    { "name": "Gisela", "image": "gisela.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Unikalus" },
    { "name": "Liselotė", "image": "liselote.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 600, "rarity": "Unikalus" },
    { "name": "Šviesos sargybinis", "image": "sviesos_sargybinis.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Unikalus" },
    { "name": "Riterių Mobilizacija", "image": "riteriu_mobilizacija.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 800, "rarity": "Unikalus" },
    { "name": "Kontrpuolimas", "image": "kontrpuolimas.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Unikalus" },
    { "name": "Garbės Priesaika", "image": "garbes_priesaika.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 300, "rarity": "Unikalus" },
    { "name": "Stiprus užnugaris", "image": "stiprus_uznugaris.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Unikalus" },
    { "name": "Brunhilda", "image": "brunhilda.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Gunteris", "image": "gunteris.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 100, "rarity": "Magiškas" },
    { "name": "Klausas", "image": "klausas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Helga", "image": "helga.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Magiškas" },
    { "name": "Margareta", "image": "margareta.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Pulko sargyba", "image": "pulko_sargyba.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 600, "rarity": "Magiškas" },
    { "name": "Adelheida", "image": "adelheida.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 100, "rarity": "Paprastas" },
    { "name": "Hildegardas", "image": "hildegardas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 300, "rarity": "Paprastas" },
    { "name": "Frieda", "image": "frieda.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Paprastas" },
    { "name": "Irmugarda", "image": "irmugarda.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 200, "rarity": "Paprastas" },
    { "name": "Aneliesė", "image": "aneliese.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Paprastas" },
    { "name": "Ida", "image": "ida.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 200, "rarity": "Paprastas" },
    { "name": "Miestiečių minia", "image": "miestieciu_minia.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 300, "rarity": "Paprastas" },
    { "name": "Įkvepianti kalba", "image": "ikvepianti_kalba.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Paprastas" },
    { "name": "Teisiantis žvilgsnis", "image": "teisiantis_zvilgsnis.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 300, "rarity": "Paprastas" },
    { "name": "Meistras Domura", "image": "meistras_domura.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Legendinis" },
    { "name": "Azusaki", "image": "azusaki.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 800, "rarity": "Legendinis" },
    { "name": "Isekono", "image": "isekono.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Epiškas" },
    { "name": "Rikito", "image": "rikito.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 600, "rarity": "Epiškas" },
    { "name": "Ribe", "image": "ribe.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 600, "rarity": "Epiškas" },
    { "name": "Kyose", "image": "kyose.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 700, "rarity": "Epiškas" },
    { "name": "Keimasa", "image": "keimasa.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Unikalus" },
    { "name": "Narigawa", "image": "narigawa.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 500, "rarity": "Unikalus" },
    { "name": "Sadakumo", "image": "sadakumo.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 600, "rarity": "Unikalus" },
    { "name": "Netikėtas smūgis", "image": "netiketas_smugis.png", "type": "Burtas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Unikalus" },
    { "name": "Isodera", "image": "isodera.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Magiškas" },
    { "name": "Tokinore", "image": "tokinore.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Magiškas" },
    { "name": "Yasunore", "image": "yasunore.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 900, "rarity": "Magiškas" },
    { "name": "Tsurano", "image": "tsurano.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Tomikida", "image": "tomikida.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Magiškas" },
    { "name": "Atsurai", "image": "atsurai.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 500, "rarity": "Magiškas" },
    { "name": "Fururuno", "image": "fururuno.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 600, "rarity": "Magiškas" },
    { "name": "Nidiri", "image": "nidiri.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Uramami", "image": "uramami.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Toguchi", "image": "toguchi.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Keihito", "image": "keihito.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 200, "rarity": "Magiškas" },
    { "name": "Tahata", "image": "tahata.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 500, "rarity": "Magiškas" },
    { "name": "Kainiko", "image": "kainiko.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Gitori", "image": "gitori.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 500, "rarity": "Magiškas" },
    { "name": "Užnugario Ataka", "image": "uznugario_ataka.png", "type": "Burtas", "faction": "Rytų vėjas", "cost": 500, "rarity": "Magiškas" },
    { "name": "Mitsudiri", "image": "mitsudiri.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Paprastas" },
    { "name": "Naotsuo", "image": "naotsuo.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 200, "rarity": "Paprastas" },
    { "name": "Takashai", "image": "takashai.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Paprastas" },
    { "name": "Narunso", "image": "narunso.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Paprastas" },
    { "name": "Chimi", "image": "chimi.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 100, "rarity": "Paprastas" },
    { "name": "Svantonas Lazaras", "image": "svantonas_lazaras.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 600, "rarity": "Legendinis" },
    { "name": "Krofordas Rūstusis", "image": "krofordas_rustusis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 700, "rarity": "Legendinis" },
    { "name": "Juodmūšis Žiaurusis", "image": "juodmusis_ziaurusis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 700, "rarity": "Epiškas" },
    { "name": "Kapitonas Juodragis", "image": "kapitonas_juodragis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 800, "rarity": "Epiškas" },
    { "name": "Žiežarė Varnė", "image": "ziezare_varne.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 600, "rarity": "Epiškas" },
    { "name": "Grizmas Šmėklinis", "image": "grizmas_smeklinis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 500, "rarity": "Epiškas" },
    { "name": "Kulvinas Kirvarža", "image": "kulvinas_kirvarza.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 400, "rarity": "Unikalus" },
    { "name": "Rūskė Aidė", "image": "ruske_aide.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 500, "rarity": "Unikalus" },
    { "name": "Gylis Paslaptingasis", "image": "gylis_paslaptingasis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 700, "rarity": "Unikalus" },
    { "name": "Griausminė Grikštė", "image": "griausmine_grikste.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 400, "rarity": "Unikalus" },
    { "name": "Prakeiktas auksas", "image": "prakeiktas_auksas.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 700, "rarity": "Unikalus" },
    { "name": "Kapitono paslaptis", "image": "kapitono_paslaptis.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Unikalus" },
    { "name": "Krofordo relikvijos", "image": "krofordo_relikvijos.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 500, "rarity": "Unikalus" },
    { "name": "Juodvėrė Mirla", "image": "juodvere_mirla.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 600, "rarity": "Magiškas" },
    { "name": "Drūzas Kirvarža", "image": "druzas_kirvarza.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 500, "rarity": "Magiškas" },
    { "name": "Staugirdas Klasta", "image": "staugirdas_klasta.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 400, "rarity": "Magiškas" },
    { "name": "Vilkė Šėlsminė", "image": "vilke_selsmine.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Magiškas" },
    { "name": "Žėltma Šarmė", "image": "zeltma_sarme.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 400, "rarity": "Magiškas" },
    { "name": "Smakas Klampynas", "image": "smakas_klampynas.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Magiškas" },
    { "name": "Patrankas pridegt!", "image": "patrankas_pridegt.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 400, "rarity": "Magiškas" },
    { "name": "Jungos agonija", "image": "jungos_agonija.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Magiškas" },
    { "name": "Jūros šmėklos lobis", "image": "juros_smeklos_lobis.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Magiškas" },
    { "name": "Paslaptinga skrynelė", "image": "paslaptinga_skrynele.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 100, "rarity": "Magiškas" },
    { "name": "Netikėtos relikvijos", "image": "netiketos_relikvijos.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Magiškas" },
    { "name": "Grobio dalybos", "image": "grobio_dalybos.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 200, "rarity": "Magiškas" },
    { "name": "Dargis Ištras", "image": "dargis_istras.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 200, "rarity": "Paprastas" },
    { "name": "Mirtulė Aura", "image": "mirtule_aura.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 100, "rarity": "Paprastas" },
    { "name": "Lutis Dolcas", "image": "lutis_dolcas.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 100, "rarity": "Paprastas" },
    { "name": "Gluodas Gilunis", "image": "gluodas_gilunis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 500, "rarity": "Paprastas" },
    { "name": "Laivo apskaita", "image": "laivo_apskaita.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Paprastas" },
    { "name": "Inkvizitorius Madielius", "image": "inkvizitorius_madielius.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 600, "rarity": "Legendinis" },
    { "name": "Inkvizitorius Liofanas", "image": "inkvizitorius_liofanas.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 600, "rarity": "Legendinis" },
    { "name": "Tėvas Konstancijus", "image": "tevas_konstancijus.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 400, "rarity": "Epiškas" },
    { "name": "Albas Griaustinskydis", "image": "albas_griaustinskydis.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Epiškas" },
    { "name": "Dieviškoji aušra", "image": "dieviskoji_ausra.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 600, "rarity": "Epiškas" },
    { "name": "Gydantis Žibintas", "image": "gydantis_zibintas.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 600, "rarity": "Epiškas" },
    { "name": "Šventoji Ranka", "image": "sventoji_ranka.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 400, "rarity": "Epiškas" },
    { "name": "Klemensas Hilgardas", "image": "klemensas_hilgardas.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Unikalus" },
    { "name": "Teodoras Ateljukas", "image": "teodoras_ateljukas.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Unikalus" },
    { "name": "Vilijus Morifadzė", "image": "vilijus_morifadze.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 600, "rarity": "Unikalus" },
    { "name": "Inkvizicijos riteris", "image": "inkvizicijos_riteris.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Unikalus" },
    { "name": "Bažnyčios šauklys", "image": "baznycios_sauklys.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Unikalus" },
    { "name": "Amžinoji Palaima", "image": "amzinoji_palaima.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 400, "rarity": "Unikalus" },
    { "name": "Angeliška Apsauga", "image": "angeliska_apsauga.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Unikalus" },
    { "name": "Dagnė Šviesnešė", "image": "dagne_sviesnese.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Emilija Saulėtakė", "image": "emilija_sauletake.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 400, "rarity": "Magiškas" },
    { "name": "Dolvydas Malda", "image": "dolvydas_malda.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Rogandas Maldinis", "image": "rogandas_maldinis.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Magiškas" },
    { "name": "Žemigijus Tolietis", "image": "zemigijus_tolietis.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 600, "rarity": "Magiškas" },
    { "name": "Baltramiejus Kelmas", "image": "baltramiejus_kelmas.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 400, "rarity": "Magiškas" },
    { "name": "Šventasis Skydas", "image": "sventasis_skydas.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Magiškas" },
    { "name": "Angeliškas švytėjimas", "image": "angeliskas_svytejimas.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Paprastas" },
    { "name": "Gerardas Malynas", "image": "gerardas_malynas.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 100, "rarity": "Paprastas" },
    { "name": "Rimgaudas Servas", "image": "rimgaudas_servas.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 200, "rarity": "Paprastas" },
    { "name": "Liucijus Dorys", "image": "liucijus_dorys.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 200, "rarity": "Paprastas" },
    { "name": "Taldas Giedragynis", "image": "taldas_giedragynis.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 200, "rarity": "Paprastas" },
    { "name": "Laukūnas Artibatis", "image": "laukunas_artibatis.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 600, "rarity": "Paprastas" },
    { "name": "Mundmantas Durpė", "image": "mundmantas_durpe.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 700, "rarity": "Paprastas" },
{ "name": "Birmantas Skribalis", "image": "birmantas_skribalis.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 100, "rarity": "Paprastas" },
{ "name": "Šventieji skaitiniai", "image": "sventieji_skaitiniai.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 200, "rarity": "Magiškas" },
{ "name": "Grafas Liuteris", "image": "grafas_liuteris.png", "type": "Veikėjas", "faction": "Universalus", "cost": 600, "rarity": "Legendinis" },
{ "name": "Ugnikalnio sargybinis", "image": "ugnikalnio_sargybinis.png", "type": "Veikėjas", "faction": "Universalus", "cost": 700, "rarity": "Epiškas" },
{ "name": "Kalnų trolis", "image": "kalnu_trolis.png", "type": "Veikėjas", "faction": "Universalus", "cost": 600, "rarity": "Epiškas" },
{ "name": "Feniksas", "image": "feniksas.png", "type": "Veikėjas", "faction": "Universalus", "cost": 300, "rarity": "Epiškas" },
{ "name": "Šerkšnadūmis", "image": "serksnadumis.png", "type": "Veikėjas", "faction": "Universalus", "cost": 500, "rarity": "Epiškas" },
{ "name": "Laukinė magija", "image": "laukine_magija.png", "type": "Burtas", "faction": "Universalus", "cost": 500, "rarity": "Epiškas" },
{ "name": "Laikinasis skydas", "image": "laikinasis_skydas.png", "type": "Burtas", "faction": "Universalus", "cost": 300, "rarity": "Epiškas" },
{ "name": "Akmeninis sargas", "image": "akmeninis_sargas.png", "type": "Veikėjas", "faction": "Universalus", "cost": 400, "rarity": "Unikalus" },
{ "name": "Akmens golemas", "image": "akmens_golemas.png", "type": "Veikėjas", "faction": "Universalus", "cost": 700, "rarity": "Unikalus" },
{ "name": "Baronas Draganis", "image": "baronas_draganis.png", "type": "Veikėjas", "faction": "Universalus", "cost": 700, "rarity": "Unikalus" },
{ "name": "Keistos šviesos", "image": "keistos_sviesos.png", "type": "Burtas", "faction": "Universalus", "cost": 600, "rarity": "Unikalus" },
{ "name": "Ugninė valia", "image": "ugnine_valia.png", "type": "Burtas", "faction": "Universalus", "cost": 400, "rarity": "Unikalus" },
{ "name": "Kabum!", "image": "kabum.png", "type": "Burtas", "faction": "Universalus", "cost": 500, "rarity": "Unikalus" },
{ "name": "Burfas", "image": "burfas.png", "type": "Veikėjas", "faction": "Universalus", "cost": 300, "rarity": "Magiškas" },
{ "name": "Pelkių vilkas", "image": "pelkiu_vilkas.png", "type": "Veikėjas", "faction": "Universalus", "cost": 500, "rarity": "Magiškas" },
{ "name": "Riteris fantomas", "image": "riteris_fantomas.png", "type": "Veikėjas", "faction": "Universalus", "cost": 400, "rarity": "Magiškas" },
{ "name": "Salvija Morta", "image": "salvija_morta.png", "type": "Veikėjas", "faction": "Universalus", "cost": 300, "rarity": "Magiškas" },
{ "name": "Adaras", "image": "adaras.png", "type": "Veikėjas", "faction": "Universalus", "cost": 500, "rarity": "Magiškas" },
{ "name": "Speigabarzdis", "image": "speigabarzdis.png", "type": "Veikėjas", "faction": "Universalus", "cost": 700, "rarity": "Magiškas" },
{ "name": "Hercogienė Amelija", "image": "hercogiene_amelija.png", "type": "Veikėjas", "faction": "Universalus", "cost": 500, "rarity": "Magiškas" },
{ "name": "Sprogimo banga", "image": "sprogimo_banga.png", "type": "Burtas", "faction": "Universalus", "cost": 300, "rarity": "Magiškas" },
{ "name": "Gydanti aura", "image": "gydanti_aura.png", "type": "Burtas", "faction": "Universalus", "cost": 200, "rarity": "Magiškas" },
{ "name": "Gobšiaus grobis", "image": "gobsiaus_grobis.png", "type": "Burtas", "faction": "Universalus", "cost": 400, "rarity": "Magiškas" },
{ "name": "Kaimietis", "image": "kaimietis.png", "type": "Veikėjas", "faction": "Universalus", "cost": 100, "rarity": "Paprastas" },
{ "name": "Keliaujantis samdinys", "image": "keliaujantis_samdinys.png", "type": "Veikėjas", "faction": "Universalus", "cost": 400, "rarity": "Paprastas" },
{ "name": "Tilvija Muzilė", "image": "tilvija_muzile.png", "type": "Veikėjas", "faction": "Universalus", "cost": 200, "rarity": "Paprastas" },
{ "name": "Vilkžmogis", "image": "vilkzmogis.png", "type": "Veikėjas", "faction": "Universalus", "cost": 300, "rarity": "Paprastas" },
{ "name": "Žilakailis", "image": "zilakailis.png", "type": "Veikėjas", "faction": "Universalus", "cost": 500, "rarity": "Paprastas" },
{ "name": "Ragagunis", "image": "ragagunis.png", "type": "Veikėjas", "faction": "Universalus", "cost": 700, "rarity": "Paprastas" },
{ "name": "Amžių skydas", "image": "amziu_skydas.png", "type": "Artefaktas", "faction": "Universalus", "cost": 400, "rarity": "Epiškas" },
{ "name": "Žinių akmuo", "image": "ziniu_akmuo.png", "type": "Artefaktas", "faction": "Universalus", "cost": 400, "rarity": "Unikalus" },
{ "name": "Magmos širdis", "image": "magmos_sirdis.png", "type": "Artefaktas", "faction": "Universalus", "cost": 300, "rarity": "Unikalus" },
{ "name": "Amžinosios ugnies akis", "image": "amzinosios_ugnes_akis.png", "type": "Artefaktas", "faction": "Universalus", "cost": 300, "rarity": "Unikalus" },
{ "name": "Vidurnakčio talismanas", "image": "vidurnakcio_talismanas.png", "type": "Artefaktas", "faction": "Universalus", "cost": 300, "rarity": "Unikalus" },
{ "name": "Ledo kristalas", "image": "ledo_kristalas.png", "type": "Artefaktas", "faction": "Universalus", "cost": 400, "rarity": "Unikalus" },
{ "name": "Gelmių Kristalas", "image": "gelmiu_kristalas.png", "type": "Artefaktas", "faction": "Universalus", "cost": 500, "rarity": "Magiškas" },
{ "name": "Nakties vėjų kompasas", "image": "nakties_veju_kompasas.png", "type": "Artefaktas", "faction": "Mirties maršas", "cost": 300, "rarity": "Unikalus" },
{ "name": "Kapinių žibintas", "image": "kapiniu_zibintas.png", "type": "Artefaktas", "faction": "Mirties maršas", "cost": 400, "rarity": "Unikalus" },
{ "name": "Nekromanto amuletas", "image": "nekromanto_amuletas.png", "type": "Artefaktas", "faction": "Mirties maršas", "cost": 400, "rarity": "Magiškas" },
{ "name": "Kankintojo kirvis", "image": "kankintojo_kirvis.png", "type": "Artefaktas", "faction": "Demonų orda", "cost": 400, "rarity": "Unikalus" },
{ "name": "Kančių knyga", "image": "kanciu_knyga.png", "type": "Artefaktas", "faction": "Demonų orda", "cost": 300, "rarity": "Magiškas" },
{ "name": "Kapitono teleskopas", "image": "kapitono_teleskopas.png", "type": "Artefaktas", "faction": "Plėšikų naktis", "cost": 500, "rarity": "Unikalus" },
{ "name": "Jungos plunksna", "image": "jungos_plunksna.png", "type": "Artefaktas", "faction": "Plėšikų naktis", "cost": 400, "rarity": "Magiškas" },
{ "name": "Sprogiosios statinės", "image": "sprogiosios_statines.png", "type": "Artefaktas", "faction": "Vryhiok'o gauja", "cost": 400, "rarity": "Unikalus" },
{ "name": "Sprogmenų dėžutė", "image": "sprogmenu_dezute.png", "type": "Artefaktas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Magiškas" },
{ "name": "Garbės šalmas", "image": "garbes_salmas.png", "type": "Artefaktas", "faction": "Šviesos pulkas", "cost": 500, "rarity": "Magiškas" },
{ "name": "Įšventinimo kalavijas", "image": "isventinimo_kalavijas.png", "type": "Artefaktas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Unikalus" },
{ "name": "Magiškas portalas", "image": "magiskas_portalas.png", "type": "Artefaktas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Unikalus" },
{ "name": "Speigo lazda", "image": "speigo_lazda.png", "type": "Artefaktas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Magiškas" },
{ "name": "Pranašo kryžius", "image": "pranaso_kryzius.png", "type": "Artefaktas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Unikalus" },
{ "name": "Inkvizicijos knyga", "image": "inkvizicijos_knyga.png", "type": "Artefaktas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Magiškas" },
{ "name": "Šėšėlio batai", "image": "seselio_batai.png", "type": "Artefaktas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Magiškas" },
{ "name": "Dūmų bomba", "image": "dumu_bomba.png", "type": "Artefaktas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Magiškas" },
{ "name": "Inkvizicijos bokštas", "image": "inkvizicijos_bokstas.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Unikalus" },
{ "name": "Elys Matviga", "image": "elys_matviga.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Unikalus" },
{ "name": "Bunikardas Vaga", "image": "bunikardas_vaga.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 700, "rarity": "Magiškas" },
{ "name": "Elmūras Milindzė", "image": "elmuras_milindze.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Magiškas" },
{ "name": "Šventasis įkvėpimas", "image": "sventasis_ikvepimas.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 400, "rarity": "Magiškas" },
{ "name": "Šventoji rykštė", "image": "sventoji_rykste.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Magiškas" },
{ "name": "Šviesos Palaiminimas", "image": "sviesos_palaiminimas.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Magiškas" },
{ "name": "Morisas Griaustinkalbis", "image": "morisas_griaustinkalbis.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 500, "rarity": "Paprastas" },
{ "name": "Begnas Auksaspiegys", "image": "begnas_auksaspiegys.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Paprastas" },
{ "name": "Inkvizicijos misionierius", "image": "inkvizicijos_misionierius.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Dulvydas Dėtė", "image": "dulvydas_dete.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Tauricijus Amilas Gėtė", "image": "tauricijus_amilas_gete.png", "type": "Veikėjas", "faction": "Inkvizicijos legionas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Inkvizitoriaus Išmintis", "image": "inkvizitoriaus_ismintis.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Atsitraukimas", "image": "atsitraukimas.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 300, "rarity": "Paprastas" },
{ "name": "Apvaizda", "image": "apvaizda.png", "type": "Burtas", "faction": "Inkvizicijos legionas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Barbadosas Klintas", "image": "barbadosas_klintas.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 500, "rarity": "Unikalus" },
{ "name": "Baltvilis Žiaurusis", "image": "baltvilis_ziaurusis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 500, "rarity": "Unikalus" },
{ "name": "Kapitono padėjėja", "image": "kapitono_padejeja.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Unikalus" },
{ "name": "Žaibo Plunksna", "image": "zaibo_plunksna.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 600, "rarity": "Magiškas" },
{ "name": "Munčis chebrantas", "image": "muncis_chebrantas.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 200, "rarity": "Magiškas" },
{ "name": "Apsukrusis Drakšlys", "image": "apsukrusis_drakslys.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 100, "rarity": "Magiškas" },
{ "name": "Vilpūras Semis", "image": "vilpuras_semis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 400, "rarity": "Magiškas" },
{ "name": "Irga Įžūlė", "image": "irga_izule.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 200, "rarity": "Magiškas" },
{ "name": "Kapitonas Kernis", "image": "kapitonas_kernis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 500, "rarity": "Magiškas" },
{ "name": "Azura Miklioji", "image": "azura_miklioji.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 200, "rarity": "Magiškas" },
{ "name": "Gelgaudas Audra", "image": "gelgaudas_audra.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 600, "rarity": "Paprastas" },
{ "name": "Piratas Marodierius", "image": "piratas_marodierius.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 100, "rarity": "Paprastas" },
{ "name": "Piratas žvalgas", "image": "piratas_zvalgas.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 100, "rarity": "Paprastas" },
{ "name": "Piratas raitelis", "image": "piratas_raitelis.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Paprastas" },
{ "name": "Kuršas Žaibas", "image": "kursas_zaibas.png", "type": "Veikėjas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Paprastas" },
{ "name": "Egzekucija", "image": "egzekucija.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 100, "rarity": "Paprastas" },
{ "name": "Pirmyn!", "image": "pirmyn.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 300, "rarity": "Paprastas" },
{ "name": "Leisk man!", "image": "leisk_man.png", "type": "Burtas", "faction": "Plėšikų naktis", "cost": 200, "rarity": "Paprastas" },
{ "name": "Kapinių nekromantas", "image": "kapiniu_nekromantas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Unikalus" },
{ "name": "Išprotėjas nekromantas", "image": "isprotejas_nekromantas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 300, "rarity": "Unikalus" },
{ "name": "Kapinių ragana", "image": "kapiniu_ragana.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 600, "rarity": "Magiškas" },
{ "name": "Zombis golemas", "image": "zombis_golemas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 700, "rarity": "Magiškas" },
{ "name": "Dr. Krudžas", "image": "dr_krudzas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 200, "rarity": "Magiškas" },
{ "name": "Mirties šamanė", "image": "mirties_samane.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 100, "rarity": "Magiškas" },
{ "name": "Nelaukta draugija", "image": "nelaukta_draugija.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 400, "rarity": "Magiškas" },
{ "name": "Nekrotinė bomba", "image": "nekrotine_bomba.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 300, "rarity": "Magiškas" },
{ "name": "Zombis sargas", "image": "zombis_sargas.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 100, "rarity": "Paprastas" },
{ "name": "Zombis", "image": "zombis.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 100, "rarity": "Paprastas" },
{ "name": "Zombis kariškis", "image": "zombis_kariskis.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Nutrūktgalvis Benis", "image": "nutrukgalvis_benis.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Anabolinis zombis", "image": "anabolinis_zombis.png", "type": "Veikėjas", "faction": "Mirties maršas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Vampyrizmas", "image": "vampyrizmas.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 300, "rarity": "Paprastas" },
{ "name": "Liepsnos kamuolys", "image": "liepsnos_kamuolys.png", "type": "Burtas", "faction": "Mirties maršas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Zefiksas Kulternis", "image": "zefiksas_kulternis.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 600, "rarity": "Unikalus" },
{ "name": "Didysis Edidalfas", "image": "didysis_edidalfas.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 700, "rarity": "Unikalus" },
{ "name": "Gydūnė Džilė", "image": "gydune_dzile.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 100, "rarity": "Magiškas" },
{ "name": "Milva Sarvilė", "image": "milva_sarvile.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 200, "rarity": "Magiškas" },
{ "name": "Ilfas Kintas", "image": "ilfas_kintas.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 200, "rarity": "Magiškas" },
{ "name": "Tornadas", "image": "tornadas.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 600, "rarity": "Magiškas" },
{ "name": "Ugnies kamuolys", "image": "ugnies_kamuolys.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 600, "rarity": "Magiškas" },
{ "name": "Liepsnos liežuviai", "image": "liepsnos_liezuviai.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Magiškas" },
{ "name": "Stingdantis kristalas", "image": "stingdantis_kristalas.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 200, "rarity": "Magiškas" },
{ "name": "Salivija Zilda", "image": "salivija_zilda.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 200, "rarity": "Paprastas" },
{ "name": "Milfredas Senasis", "image": "milfredas_senasis.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 200, "rarity": "Paprastas" },
{ "name": "Noras Tamietis", "image": "noras_tamietis.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Paprastas" },
{ "name": "Gurvydas Grifas", "image": "gurvydas_grifas.png", "type": "Veikėjas", "faction": "Mistikos melodija", "cost": 500, "rarity": "Paprastas" },
{ "name": "Žaibo iškrova", "image": "zaibo_iskrova.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 100, "rarity": "Paprastas" },
{ "name": "Ugnies pliūpsnis", "image": "ugnies_pliupsnis.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 100, "rarity": "Paprastas" },
{ "name": "Aptikti magiją", "image": "aptikti_magija.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 100, "rarity": "Paprastas" },
{ "name": "Naujos žinios", "image": "naujos_zinios.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Paprastas" },
{ "name": "Tylos!", "image": "tylos.png", "type": "Burtas", "faction": "Mistikos melodija", "cost": 300, "rarity": "Paprastas" },
{ "name": "Ryu", "image": "ryu.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 700, "rarity": "Unikalus" },
{ "name": "Kenji", "image": "kenji.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 500, "rarity": "Unikalus" },
{ "name": "Natsumi", "image": "natsumi.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Magiškas" },
{ "name": "Midori", "image": "midori.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Magiškas" },
{ "name": "Hikage", "image": "hikage.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 200, "rarity": "Magiškas" },
{ "name": "Netikras atsitraukimas", "image": "netikras_atsitraukimas.png", "type": "Burtas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Magiškas" },
{ "name": "Nindzė žvalgas", "image": "nindze_zvalgas.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 100, "rarity": "Paprastas" },
{ "name": "Kazuma", "image": "kazuma.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Raiden", "image": "raiden.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Paprastas" },
{ "name": "Hotaru", "image": "hotaru.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Paprastas" },
{ "name": "Takumi", "image": "takumi.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Aiko", "image": "aiko.png", "type": "Veikėjas", "faction": "Rytų vėjas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Dūmų uždanga", "image": "dumų_uzdanga.png", "type": "Burtas", "faction": "Rytų vėjas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Meditacija", "image": "meditacija.png", "type": "Burtas", "faction": "Rytų vėjas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Tylusis metodas", "image": "tylusis_metodas.png", "type": "Burtas", "faction": "Rytų vėjas", "cost": 300, "rarity": "Paprastas" },
{ "name": "Generolas Budolfas", "image": "generolas_budolfas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Unikalus" },
{ "name": "Heilderbergo bokštas", "image": "heilderbergo_bokstas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 600, "rarity": "Unikalus" },
{ "name": "Seras Hoftmanas", "image": "seras_hoftmanas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Unikalus" },
{ "name": "Skydo mergelė", "image": "skydo_mergele.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 100, "rarity": "Magiškas" },
{ "name": "Riteris gynėjas", "image": "riteris_gynejas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 200, "rarity": "Magiškas" },
{ "name": "Ginklanešė Ulma", "image": "ginklanese_ulma.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 200, "rarity": "Magiškas" },
{ "name": "Riteris", "image": "riteris.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Gizela Amelietė", "image": "gizela_ameliete.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Otas Fenbaueris", "image": "otas_fenbaueris.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 600, "rarity": "Paprastas" },
{ "name": "Olafas Burgas", "image": "olafas_burgas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 300, "rarity": "Paprastas" },
{ "name": "Meidija", "image": "meidija.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Ulvydas Kantrusis", "image": "ulvydas_kantrusis.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Aršusis Manufas", "image": "arsusis_manufas.png", "type": "Veikėjas", "faction": "Šviesos pulkas", "cost": 600, "rarity": "Paprastas" },
{ "name": "Jėgos eleksyras", "image": "jegos_eleksyras.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 400, "rarity": "Paprastas" },
{ "name": "Strėlių lietus", "image": "streliu_lietus.png", "type": "Burtas", "faction": "Šviesos pulkas", "cost": 200, "rarity": "Paprastas" },
{ "name": "Vadas Vryhiok’as", "image": "vadas_vryhiokas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 700, "rarity": "Unikalus" },
{ "name": "Glort’as", "image": "glortas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 600, "rarity": "Magiškas" },
{ "name": "Kruigex’as", "image": "kruigexas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 500, "rarity": "Magiškas" },
{ "name": "Goblinas maitėda", "image": "goblinas_maiteda.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Magiškas" },
{ "name": "Gnegs’as", "image": "gnegsas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 200, "rarity": "Magiškas" },
{ "name": "Goblinų įniršis", "image": "goblinu_inirsis.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 400, "rarity": "Magiškas" },
{ "name": "Ledo spindulys", "image": "ledo_spindulys.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 200, "rarity": "Magiškas" },
{ "name": "Magmos granata", "image": "magmos_granata.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 500, "rarity": "Magiškas" },
{ "name": "Goblinas žvalgas", "image": "goblinas_zvalgas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 100, "rarity": "Paprastas" },
{ "name": "Goblinas tykotojas", "image": "goblinas_tykotojas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 200, "rarity": "Paprastas" },
{ "name": "Gnaard’as", "image": "gnaardas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Paprastas" },
{ "name": "Shiarxi", "image": "shiarxi.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Paprastas" },
{ "name": "Hokieg’as", "image": "hokiegas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 300, "rarity": "Paprastas" },
{ "name": "Dagberd’as", "image": "dagberdas.png", "type": "Veikėjas", "faction": "Vryhiok'o gauja", "cost": 500, "rarity": "Paprastas" },
{ "name": "Pasala", "image": "pasala.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 400, "rarity": "Paprastas" },
{ "name": "Chaoso pakylėtas", "image": "chaoso_pakyletas.png", "type": "Burtas", "faction": "Vryhiok'o gauja", "cost": 500, "rarity": "Paprastas" },
{ "name": "Ongromig’as", "image": "ongromigas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 700, "rarity": "Unikalus" },
{ "name": "Dolgid’as", "image": "dolgidas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 600, "rarity": "Unikalus" },
{ "name": "Astrareg’as", "image": "astraregas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 500, "rarity": "Unikalus" },
{ "name": "Alfa pragaro skalikas", "image": "alfa_pragaro_skalikas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 400, "rarity": "Magiškas" },
{ "name": "Korkodeg’as", "image": "korkodegas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 200, "rarity": "Magiškas" },
{ "name": "Impas", "image": "impas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 100, "rarity": "Magiškas" },
{ "name": "Aukos mentalitetas", "image": "aukos_mentalitetas.png", "type": "Burtas", "faction": "Demonų orda", "cost": 300, "rarity": "Magiškas" },
{ "name": "Gniuždantis žvilgsnis", "image": "gniuzdantis_zvilgsnis.png", "type": "Burtas", "faction": "Demonų orda", "cost": 400, "rarity": "Magiškas" },
{ "name": "Demono apgavystė", "image": "demono_apgavyste.png", "type": "Burtas", "faction": "Demonų orda", "cost": 300, "rarity": "Magiškas" },
{ "name": "Gyvasties išsiurbimas", "image": "gyvasties_issiurbimas.png", "type": "Burtas", "faction": "Demonų orda", "cost": 400, "rarity": "Magiškas" },
{ "name": "Pragaro skalikas", "image": "pragaro_skalikas.png", "type": "Veikėjas", "faction": "Demonų orda", "cost": 200, "rarity": "Paprastas" },
{ "name": "Gobšumas", "image": "gobsumas.png", "type": "Burtas", "faction": "Demonų orda", "cost": 400, "rarity": "Paprastas" },
{ "name": "Demono įgėlimas", "image": "demono_igelimas.png", "type": "Burtas", "faction": "Demonų orda", "cost": 200, "rarity": "Paprastas" },
{ "name": "Relikto išardymas", "image": "relikto_isardymas.png", "type": "Burtas", "faction": "Universalus", "cost": 500, "rarity": "Unikalus" },
{ "name": "Demonų šmėkla", "image": "demonu_smekla.png", "type": "Burtas", "faction": "Demonų orda", "cost": 300, "rarity": "Paprastas" },
{ "name": "Demoniškas maras", "image": "demoniskas_maras.png", "type": "Burtas", "faction": "Demonų orda", "cost": 400, "rarity": "Paprastas" }

];

function displayCards(cardsToDisplay) {
    const cardContainer = document.getElementById("cardContainer");
    cardContainer.innerHTML = "";
    
    if (cardsToDisplay.length === 0) {
        cardContainer.innerHTML = "<p>Nerasta rezultatų.</p>";
        return;
    }

    cardsToDisplay.forEach(card => {
        const cardElement = document.createElement("div");
        cardElement.classList.add("card");
        cardElement.innerHTML = `
            <img src="${card.image}" alt="${card.name}">
            <p class="rarity ${getRarityClass(card.rarity)}">${card.rarity}</p>
            <h3>${card.name}</h3>
            <p>Frakcija: ${card.faction}</p>
            <p>Kaina: ${card.cost}</p>
        `;
        cardContainer.appendChild(cardElement);
    });
}

function getRarityClass(rarity) {
    switch (rarity) {
        case "Legendinis": return "legendinis";
        case "Epiškas": return "episkas";
        case "Unikalus": return "unikalus";
        case "Magiškas": return "magiskas";
        case "Paprastas": return "paprastas";
        default: return "";
    }
}

function filterCards() {
    const factionFilter = document.getElementById("factionFilter").value;
    const typeFilter = document.getElementById("typeFilter").value;
    const costFilter = document.getElementById("costFilter").value;
    const rarityFilter = document.getElementById("rarityFilter").value;
    const searchQuery = document.getElementById("searchBox").value.trim().toLowerCase();

    const filteredCards = cards.filter(card => {
        const matchesFaction = !factionFilter || factionFilter === "Visos" || card.faction === factionFilter;
        const matchesType = !typeFilter || typeFilter === "Visi" || card.type === typeFilter;
        const matchesCost = !costFilter || costFilter === "Visi" || card.cost == costFilter;
        const matchesRarity = !rarityFilter || rarityFilter === "Visi" || card.rarity === rarityFilter;
        const matchesSearch = !searchQuery || card.name.toLowerCase().includes(searchQuery);

        return matchesFaction && matchesType && matchesCost && matchesRarity && matchesSearch;
    });

    displayCards(filteredCards);
}

document.getElementById("factionFilter").addEventListener("change", filterCards);
document.getElementById("typeFilter").addEventListener("change", filterCards);
document.getElementById("costFilter").addEventListener("change", filterCards);
document.getElementById("rarityFilter").addEventListener("change", filterCards);
document.getElementById("searchBox").addEventListener("input", filterCards);

displayCards(cards);